#!/usr/bin/env bash
# Configure Nginx so that its HTTP response contains a custom header.

sudo apt-get -y update
sudo apt-get -y install nginx
sudo tee -a /etc/nginx/nginx.conf <<EOL
    add_header X-Served-By 498281-web-01;
    add_header X-Served-By 498281-web-01;
EOL

sudo service nginx restart
