#!/usr/bin/env bash
# Configure Nginx so that its HTTP response contains a custom header.

sudo apt-get -y update
sudo apt-get -y install nginx
sudo sed -i "20i \\\tadd_header X-Served-By 498281-web-01;" /etc/nginx/nginx.conf
sudo service nginx restart
